# Generated by Django 5.1.6 on 2025-03-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgex_app', '0002_alter_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(choices=[('USD', 'United States Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=20),
        ),
    ]
